unit CCE.Constants;

interface

uses
  ToolsAPI;

const
  CCE_COVERAGE_POSITION = pmmpUninstall + 200;
  CCE_COVERAGE_WIZARD_POSITION = CCE_COVERAGE_POSITION + 100;
  CCE_COVERAGE_EXECUTE_POSITION = CCE_COVERAGE_WIZARD_POSITION + 10;
  CCE_COVERAGE_HTML_POSITION = CCE_COVERAGE_EXECUTE_POSITION + 10;

  CCE_COVERAGE_CAPTION = 'Code Coverage';
  CCE_COVERAGE_WIZARD_CAPTION = 'Wizard...';
  CCE_COVERAGE_EXECUTE_CAPTION = 'Execute';
  CCE_COVERAGE_HTML_CAPTION = 'Show HTML Report';

implementation

end.
